Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2018-09, with the labels that each got.

#317 [Changelog] Update for Sprint 94
  CHANGELOG.md
Labels: documentation

#322 Don't require cloud tenant upon vApp instantiation
  app/models/manageiq/providers/vmware/cloud_manager/orchestration_template.rb
  spec/models/manageiq/providers/vmware/cloud_manager/orchestration_template_spec.rb
Labels: bug, gaprindashvili/yes

#321 Shift fog-vcloud-director version to 0.3.0
  app/models/manageiq/providers/vmware/manager_auth_mixin.rb
  manageiq-providers-vmware.gemspec
  spec/models/manageiq/providers/vmware/cloud_manager_spec.rb
  spec/models/manageiq/providers/vmware/network_manager/refresh_parser_spec.rb
Labels: enhancement

#323 [Changelog] Update for Sprint 95
  CHANGELOG.md
Labels: documentation

#324 Don't crash when probing deleted vApp for status
  app/models/manageiq/providers/vmware/cloud_manager/orchestration_stack.rb
Labels: bug, gaprindashvili/yes, hammer/yes

#326 [HAMMER] [Changelog] Update for Hammer Beta-1
  CHANGELOG.md
Labels: documentation
