Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2018-12, with the labels that each got.

#344 Bump master travis.yml to ruby 2.3.8.
  .travis.yml
Labels: gaprindashvili/yes, hammer/yes, test

#345 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-7
  CHANGELOG.md
Labels: documentation

#347 Change FactoryGirl to FactoryBot
  spec/factories/ext_management_system.rb
  spec/factories/orchestration_template.rb
  spec/factories/vm.rb
  spec/models/manageiq/providers/vmware/cloud_manager/event_catcher_spec.rb
  spec/models/manageiq/providers/vmware/cloud_manager/orchestration_service_option_converter_spec.rb
  spec/models/manageiq/providers/vmware/cloud_manager/orchestration_stack_spec.rb
  spec/models/manageiq/providers/vmware/cloud_manager/orchestration_template_spec.rb
  spec/models/manageiq/providers/vmware/cloud_manager/provision_workflow_spec.rb
  spec/models/manageiq/providers/vmware/cloud_manager/refresher_spec.rb
  spec/models/manageiq/providers/vmware/cloud_manager/vm/reconfigure_spec.rb
  spec/models/manageiq/providers/vmware/cloud_manager/vm/remote_console_spec.rb
  spec/models/manageiq/providers/vmware/cloud_manager/vm_spec.rb
  spec/models/manageiq/providers/vmware/cloud_manager_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/ems_event_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/event_catcher/runner_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/host_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/metric_capture_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/provision/cloning_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/provision/configuration/network_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/provision/customization_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/provision/placement_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/provision/state_machine_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/provision_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/provision_via_pxe/state_machine_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/provision_workflow_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresh_parser/filter_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_errors_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_storage_profile_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/vm/reconfigure_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/vm/remote_console_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/vm_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager_spec.rb
  spec/models/manageiq/providers/vmware/network_manager/refresh_parser_spec.rb
  spec/models/manageiq/providers/vmware/network_manager/refresher_spec.rb
  spec/models/miq_ems_refresh_core_worker/runner_spec.rb
  spec/models/miq_ems_refresh_core_worker_spec.rb
  spec/models/miq_vim_broker_worker/runner_spec.rb
  spec/models/miq_vim_broker_worker_spec.rb
Labels: dependencies, gaprindashvili/no, hammer/no

#348 Bump master travis.yml to ruby 2.4.5
  .travis.yml
Labels: test
