Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2018-08, with the labels that each got.

#309 Removed deprecated InventoryCollectionDefault from persister
  app/models/manageiq/providers/vmware/inventory/persister.rb
Labels: cleanup

#310 [Changelog] Update for Sprint 92
  CHANGELOG.md
Labels: documentation

#284 Don't run EmsRefresh if using streaming refresh
  app/models/manageiq/providers/vmware/infra_manager.rb
  app/models/manageiq/providers/vmware/infra_manager/refresh_worker/runner.rb
Labels: enhancement

#311 [FINE] Try to get VM UUID from summary.config or config
  app/models/manageiq/providers/vmware/infra_manager/refresh_parser.rb
  app/models/manageiq/providers/vmware/infra_manager/selector_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresh_parser_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
  spec/tools/vim_data/miq_vim_inventory/virtualMachinesByMor.yml
Labels: blocker

#314 [Changelog] Update for Gaprindashvili-5
  CHANGELOG.md
Labels: documentation
