Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2018-10, with the labels that each got.

#330 [Changelog] Update for Sprint 96
  CHANGELOG.md
Labels: documentation

#331 [GA] Don't crash when probing deleted vApp for status
  app/models/manageiq/providers/vmware/cloud_manager/orchestration_stack.rb
Labels: blocker, bug

#333 Travis - change postgres to 9.5
  .travis.yml
Labels: gaprindashvili/yes, hammer/yes
