Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2018-06, with the labels that each got.

#282 [Changelog] Update for Sprint 87
  CHANGELOG.md
Labels: documentation

#288 Persister: InventoryCollection building through add_collection()
  app/models/manageiq/providers/vmware/cloud_manager/refresh_parser.rb
  app/models/manageiq/providers/vmware/inventory/parser/cloud_manager.rb
  app/models/manageiq/providers/vmware/inventory/persister.rb
  app/models/manageiq/providers/vmware/inventory/persister/cloud_manager.rb
  app/models/manageiq/providers/vmware/inventory/persister/definitions/cloud_collections.rb
  app/models/manageiq/providers/vmware/inventory_collection_default/cloud_manager.rb
  spec/models/manageiq/providers/vmware/cloud_manager/refresher_spec.rb
Labels: refactoring

#289 [Changelog] Update for Sprint 88
  CHANGELOG.md
Labels: documentation

#285 Add method vm_move_into_folder.
  app/models/manageiq/providers/vmware/infra_manager.rb
Labels: enhancement, gaprindashvili/no

#290 Add alias for vm_remove_disk_by_file
  app/models/manageiq/providers/vmware/infra_manager.rb
Labels: enhancement

#280 Finish parsing of host properties
  app/models/manageiq/providers/vmware/infra_manager.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/inventory_collections.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/host_system.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/persister.rb
  manageiq-providers-vmware.gemspec
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
Labels: enhancement
