Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2018-11, with the labels that each got.

#334 [HAMMER] Add translations for hammer
  locale/es/ManageIQ_Providers_Vmware.po
  locale/fr/ManageIQ_Providers_Vmware.po
  locale/ja/ManageIQ_Providers_Vmware.po
  locale/pt_BR/ManageIQ_Providers_Vmware.po
  locale/zh_CN/ManageIQ_Providers_Vmware.po
Labels: internationalization

#335 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-6
  CHANGELOG.md
Labels: documentation

#338 Always set vm_or_template.connection_state
  app/models/manageiq/providers/vmware/cloud_manager/refresh_parser.rb
  app/models/manageiq/providers/vmware/cloud_manager/vm.rb
  app/models/manageiq/providers/vmware/inventory/parser/cloud_manager.rb
  spec/models/manageiq/providers/vmware/cloud_manager/refresher_spec.rb
Labels: bug

#340 [Changelog] Update for Sprint 99
  CHANGELOG.md
Labels: documentation

#336 Check EmsEvents when disconnecting storage
  app/models/manageiq/providers/vmware/infra_manager/vm_or_template_shared.rb
  app/models/manageiq/providers/vmware/infra_manager/vm_or_template_shared/disconnect.rb
Labels: blocker, bug, gaprindashvili/yes, hammer/yes

#341 [HAMMER] [Changelog] Update for Hammer RC2
  CHANGELOG.md
Labels: documentation

#343 Fix graph refresh spec test checking for orphaned
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
Labels: test
