Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2018-04, with the labels that each got.

#219 Actually apply CloudManager's api_version
  app/models/manageiq/providers/vmware/manager_auth_mixin.rb
  spec/models/manageiq/providers/vmware/cloud_manager/refresher_spec.rb
  spec/models/manageiq/providers/vmware/cloud_manager_spec.rb
Labels: enhancement, gaprindashvili/yes

#215 Add guest customization field to service catalog order form
  app/models/manageiq/providers/vmware/cloud_manager/orchestration_service_option_converter.rb
  app/models/manageiq/providers/vmware/cloud_manager/orchestration_template.rb
  app/models/manageiq/providers/vmware/cloud_manager/ovf_template.rb
  spec/models/manageiq/providers/vmware/cloud_manager/orchestration_service_option_converter_spec.rb
  spec/models/manageiq/providers/vmware/cloud_manager/orchestration_template_spec.rb
Labels: enhancement

#224 Shift fog-vcloud-director version to 0.1.10
  manageiq-providers-vmware.gemspec
Labels: enhancement, gaprindashvili/yes, unmergeable

#218 Add support for vCloud console access via WebMKS
  app/models/manageiq/providers/vmware/cloud_manager/vm.rb
  app/models/manageiq/providers/vmware/cloud_manager/vm/remote_console.rb
  spec/models/manageiq/providers/vmware/cloud_manager/vm/remote_console_spec.rb
Labels: enhancement, gaprindashvili/yes

#186 Update driven refresh
  app/models/manageiq/providers/vmware/infra_manager/inventory.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/cache.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector/inventory_cache.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/compute_resource.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/datacenter.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/datastore.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/folder.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/host_system.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/resource_pool.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/virtual_machine.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/cache_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
Labels: enhancement

#227 [FINE] Lock fog-vcloud-director gem to 0.1.8
  manageiq-providers-vmware.gemspec
Labels: dependencies

#228 [Changelog] Update for Sprint 83
  CHANGELOG.md
Labels: documentation

#230 Add supports revert to snapshot
  app/models/manageiq/providers/vmware/cloud_manager/vm.rb
  spec/models/manageiq/providers/vmware/cloud_manager_spec.rb
Labels: bug, gaprindashvili/yes

#234 Streaming refresh refactoring
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector/property_collector.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
Labels: refactoring

#235 Streaming targeted refresh tests
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/inventory_collections.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/virtual_machine.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
Labels: test

#241 [Changelog] Update for Sprint 84
  CHANGELOG.md
Labels: documentation

#217 Implement graph inventory refresh for cloud manager
  app/models/manageiq/providers/vmware/builder.rb
  app/models/manageiq/providers/vmware/cloud_manager.rb
  app/models/manageiq/providers/vmware/cloud_manager/refresher.rb
  app/models/manageiq/providers/vmware/cloud_manager/snapshot.rb
  app/models/manageiq/providers/vmware/inventory.rb
  app/models/manageiq/providers/vmware/inventory/collector.rb
  app/models/manageiq/providers/vmware/inventory/collector/cloud_manager.rb
  app/models/manageiq/providers/vmware/inventory/parser.rb
  app/models/manageiq/providers/vmware/inventory/parser/cloud_manager.rb
  app/models/manageiq/providers/vmware/inventory/persister.rb
  app/models/manageiq/providers/vmware/inventory/persister/cloud_manager.rb
  app/models/manageiq/providers/vmware/inventory_collection_default/cloud_manager.rb
  config/settings.yml
  spec/models/manageiq/providers/vmware/cloud_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/vmware/cloud_manager/refresher.yml
Labels: enhancement, gaprindashvili/yes
