Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2018-02, with the labels that each got.

#181 Network discovery probe relocation
  app/models/manageiq/providers/vmware/discovery.rb
  lib/manageiq/providers/vmware.rb
Labels: refactoring

#163 Reconfigure VM: Add / Remove Network Adapters
  app/models/manageiq/providers/vmware/infra_manager/vm.rb
  app/models/manageiq/providers/vmware/infra_manager/vm/reconfigure.rb
Labels: enhancement

#184 Added support for VM delete
  app/models/manageiq/providers/vmware/cloud_manager.rb
  app/models/manageiq/providers/vmware/cloud_manager/vm/operations.rb
  spec/models/manageiq/providers/vmware/cloud_manager/vm_spec.rb
Labels: enhancement, gaprindashvili/yes

#189 Support create snapshot for VM
  app/models/manageiq/providers/vmware/cloud_manager.rb
  app/models/manageiq/providers/vmware/cloud_manager/vm.rb
  spec/models/manageiq/providers/vmware/cloud_manager_spec.rb
Labels: enhancement, gaprindashvili/yes

#182 [Changelog] Update for Sprint 79
  CHANGELOG.md
Labels: documentation

#190 Render snapshot for VM
  app/models/manageiq/providers/vmware/cloud_manager/refresh_parser.rb
  spec/models/manageiq/providers/vmware/cloud_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/vmware/cloud_manager/refresher.yml
  spec/vcr_cassettes/manageiq/providers/vmware/network_manager/refresher.yml
Labels: enhancement, gaprindashvili/yes

#194 [Changelog] Update for Sprint 80
  CHANGELOG.md
Labels: documentation

#185 Allow vApp customization prior provisioning
  app/models/manageiq/providers/vmware/cloud_manager/orchestration_service_option_converter.rb
  app/models/manageiq/providers/vmware/cloud_manager/orchestration_stack.rb
  app/models/manageiq/providers/vmware/cloud_manager/orchestration_template.rb
  app/models/manageiq/providers/vmware/cloud_manager/ovf_template.rb
  spec/fixtures/orchestration_templates/vmware_parameters_ovf.xml
  spec/models/manageiq/providers/vmware/cloud_manager/orchestration_service_option_converter_spec.rb
  spec/models/manageiq/providers/vmware/cloud_manager/orchestration_template_spec.rb
  spec/models/manageiq/providers/vmware/cloud_manager/ovf_template_spec.rb
Labels: enhancement, gaprindashvili/yes

#193 Render hostname for vm
  app/models/manageiq/providers/vmware/cloud_manager/refresh_parser.rb
  spec/models/manageiq/providers/vmware/cloud_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/vmware/cloud_manager/refresher.yml
  spec/vcr_cassettes/manageiq/providers/vmware/network_manager/refresher.yml
Labels: enhancement, gaprindashvili/no

#196 Allow user to pick administrator password upon vApp provisioning
  app/models/manageiq/providers/vmware/cloud_manager/orchestration_service_option_converter.rb
  app/models/manageiq/providers/vmware/cloud_manager/orchestration_template.rb
  spec/models/manageiq/providers/vmware/cloud_manager/orchestration_service_option_converter_spec.rb
  spec/models/manageiq/providers/vmware/cloud_manager/orchestration_template_spec.rb
Labels: enhancement, gaprindashvili/yes
