Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2018-05, with the labels that each got.

#243 Use begin/while instead of loop do/break
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
Labels: refactoring

#252 [Changelog] Update for gaprindashvili-3 release
  CHANGELOG.md
Labels: documentation

#242 Split vApp provisioning customization into three tabs
  app/models/manageiq/providers/vmware/cloud_manager/orchestration_template.rb
  spec/models/manageiq/providers/vmware/cloud_manager/orchestration_template_spec.rb
Labels: enhancement, gaprindashvili/yes

#254 Save ems cluster for a vm
  app/models/manageiq/providers/vmware/infra_manager/inventory/cache.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/virtual_machine.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
Labels: enhancement

#258 Use new interface for targeted_scope
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
Labels: enhancement

#259 Set api_version and uid_ems in streaming refresh
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
Labels: enhancement

#256 Fix storage parsing to use datastore url
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/datastore.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/virtual_machine.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
Labels: enhancement

#257 [Changelog] Update for Sprint 85
  CHANGELOG.md
Labels: documentation

#261 Enhance disk and CPU inventoring
  app/models/manageiq/providers/vmware/cloud_manager/refresh_parser.rb
  app/models/manageiq/providers/vmware/inventory/parser/cloud_manager.rb
  app/models/manageiq/providers/vmware/inventory_collection_default/cloud_manager.rb
  app/models/manageiq/providers/vmware/network_manager/refresh_parser.rb
  manageiq-providers-vmware.gemspec
  spec/models/manageiq/providers/vmware/cloud_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/vmware/cloud_manager/refresher.yml
Labels: enhancement, gaprindashvili/yes

#262 Make nested lazy find with secondary ref work
  app/models/manageiq/providers/vmware/infra_manager/inventory/inventory_collections.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/host_system.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/virtual_machine.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
Labels: enhancement

#244 Add support for reconfigure cdrom
  app/models/manageiq/providers/vmware/infra_manager/vm.rb
  app/models/manageiq/providers/vmware/infra_manager/vm/reconfigure.rb
  spec/models/manageiq/providers/vmware/infra_manager/vm/reconfigure_spec.rb
Labels: enhancement

#263 Set the root folder's parent and set hidden/is_default for folders and resource pools
  app/models/manageiq/providers/vmware/infra_manager/inventory/inventory_collections.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/persister.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
Labels: enhancement

#267 Shift fog-vcloud-director gem version
  manageiq-providers-vmware.gemspec
Labels: enhancement, gaprindashvili/yes

#268 Add test for a vm moving to a new folder/respool
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
Labels: test

#249 Load Lans efficiently in ProvisionWorkflow
  app/models/manageiq/providers/vmware/infra_manager/provision_workflow.rb
Labels: refactoring

#269 Fixes ProvisionWorkflow#available_vlans_and_hosts
  app/models/manageiq/providers/vmware/infra_manager/provision_workflow.rb
  spec/models/manageiq/providers/vmware/infra_manager/provision_workflow_spec.rb
Labels: bug

#231 Support CPU/MEM/HDD reconfiguration
  app/models/manageiq/providers/vmware/cloud_manager.rb
  app/models/manageiq/providers/vmware/cloud_manager/vm.rb
  app/models/manageiq/providers/vmware/cloud_manager/vm/reconfigure.rb
  spec/models/manageiq/providers/vmware/cloud_manager/vm/reconfigure_spec.rb
  spec/models/manageiq/providers/vmware/cloud_manager_spec.rb
Labels: enhancement, gaprindashvili/yes

#271 Refactor relationships custom save block
  app/models/manageiq/providers/vmware/infra_manager/inventory/inventory_collections.rb
Labels: enhancement, inventory, performance

#266 Parse the lan from a guest_device
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/virtual_machine.rb
Labels: enhancement

#273 Recognize deployed vApp even if not powered on
  app/models/manageiq/providers/vmware/cloud_manager/orchestration_stack/status.rb
  spec/models/manageiq/providers/vmware/cloud_manager/orchestration_stack_spec.rb
Labels: enhancement, gaprindashvili/yes

#275 Add ems_ref_obj to streaming refresh parser
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/virtual_machine.rb
Labels: enhancement

#276 [Changelog] Update for Sprint 86
  CHANGELOG.md
Labels: documentation

#272 Reconfigure VM network connectivity aka. NICs
  app/models/manageiq/providers/vmware/cloud_manager/vm.rb
  app/models/manageiq/providers/vmware/cloud_manager/vm/reconfigure.rb
  app/models/manageiq/providers/vmware/network_manager/refresh_parser.rb
  manageiq-providers-vmware.gemspec
  spec/models/manageiq/providers/vmware/cloud_manager/vm/reconfigure_spec.rb
  spec/models/manageiq/providers/vmware/cloud_manager_spec.rb
  spec/models/manageiq/providers/vmware/network_manager/refresher_spec.rb
Labels: enhancement, gaprindashvili/yes

#279 Parse the VirtualEthernetCard model type
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/virtual_machine.rb
  app/models/manageiq/providers/vmware/infra_manager/refresh_parser.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
Labels: enhancement

#264 Bump to ruby 2.4.4 for great justice
  .travis.yml
Labels: test
