Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2018-07, with the labels that each got.

#292 [Changelog] Update for Sprint 89
  CHANGELOG.md
Labels: documentation

#293 Add debug logging for object updates from the VC
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
Labels: enhancement

#294 [Changelog] Update for Gaprindashvili-4
  CHANGELOG.md
Labels: documentation

#295 Allow streaming refresh to be enabled dynamically
  app/models/manageiq/providers/vmware/infra_manager/refresh_worker/runner.rb
Labels: enhancement

#296 Set the ems last_refresh error/time attributes
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/saver.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
Labels: enhancement

#297 Log error and backtrace if save_inventory fails
  app/models/manageiq/providers/vmware/infra_manager/inventory/saver.rb
Labels: enhancement

#298 [Changelog] Update for Sprint 90
  CHANGELOG.md
Labels: documentation

#301 Fix setting the last_refresh_date on error
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
Labels: bug

#302 Correct parent collection for custom_attributes and network
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/virtual_machine.rb
  app/models/manageiq/providers/vmware/inventory/persister/definitions/infra_collections.rb
Labels: refactoring

#305 Use the full URI for the broker connection
  app/models/manageiq/providers/vmware/infra_manager/vim_connect_mixin.rb
  app/models/manageiq/providers/vmware/infra_manager/vm_or_template_shared/scanning.rb
  app/models/miq_vim_broker_worker.rb
  app/models/miq_vim_broker_worker/runner.rb
  manageiq-providers-vmware.gemspec
  spec/models/miq_vim_broker_worker/runner_spec.rb
Labels: bug, fine/yes, gaprindashvili/yes

#306 [Changelog] Update for Sprint 91
  CHANGELOG.md
Labels: documentation
