Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2018-03, with the labels that each got.

#191 Support delete snapshot for VM
  app/models/manageiq/providers/vmware/cloud_manager.rb
  app/models/manageiq/providers/vmware/cloud_manager/vm.rb
  spec/factories/vm.rb
  spec/models/manageiq/providers/vmware/cloud_manager_spec.rb
Labels: enhancement, gaprindashvili/yes

#201 Fix VMware spec tests using have_attributes
  spec/models/manageiq/providers/vmware/cloud_manager/orchestration_service_option_converter_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/event_parser_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
Labels: test

#200 Fix deprecated use of #address
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
  app/models/manageiq/providers/vmware/infra_manager/vm/remote_console.rb
Labels: technical debt

#203 Fix collector spec nil connection comparison
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
Labels: test

#198 Skip "none" vApp network when inventoring
  app/models/manageiq/providers/vmware/network_manager/refresh_parser.rb
  spec/vcr_cassettes/manageiq/providers/vmware/network_manager/refresher.yml
Labels: bug, gaprindashvili/yes

#199 Don't run EventCatcher when "none" was selected on GUI
  app/models/manageiq/providers/vmware/cloud_manager/event_catcher.rb
  spec/factories/ext_management_system.rb
  spec/models/manageiq/providers/vmware/cloud_manager/event_catcher_spec.rb
Labels: enhancement, gaprindashvili/yes

#204 Use utility function vm_powered_on? instead manual comparison
  app/models/manageiq/providers/vmware/cloud_manager/vm/operations.rb
  spec/models/manageiq/providers/vmware/cloud_manager/vm_spec.rb
Labels: enhancement, gaprindashvili/yes

#206 Completely stop/suspend VM, not just partially
  app/models/manageiq/providers/vmware/cloud_manager/vm/operations/power.rb
  spec/models/manageiq/providers/vmware/cloud_manager/vm_spec.rb
Labels: enhancement, gaprindashvili/yes

#208 Shift fog-vcloud-director version to 0.1.9
  manageiq-providers-vmware.gemspec
Labels: enhancement, gaprindashvili/yes

#195 [GAPRINDASHVILI] Inventory VM hostname to name
  app/models/manageiq/providers/vmware/cloud_manager/refresh_parser.rb
  spec/models/manageiq/providers/vmware/cloud_manager/refresher_spec.rb
  spec/models/manageiq/providers/vmware/network_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/vmware/cloud_manager/refresher.yml
  spec/vcr_cassettes/manageiq/providers/vmware/network_manager/refresher.yml
Labels: enhancement

#207 Update disk's controller type parsing
  app/models/manageiq/providers/vmware/cloud_manager/refresh_parser.rb
  spec/models/manageiq/providers/vmware/cloud_manager/refresher_spec.rb
Labels: enhancement, gaprindashvili/yes

#210 [Changelog] Update for Sprint 81
  CHANGELOG.md
Labels: documentation

#159 Move VimConnectMixin to VMware repo
  app/models/manageiq/providers/vmware/infra_manager/host.rb
  app/models/manageiq/providers/vmware/infra_manager/vim_connect_mixin.rb
Labels: refactoring

#214 Fix update driven vm refresh operating systems
  app/models/manageiq/providers/vmware/infra_manager/inventory/inventory_collections.rb
Labels: bug

#209 Prevent vapp templates from being duplicated
  app/models/manageiq/providers/vmware/cloud_manager/orchestration_template.rb
  app/models/manageiq/providers/vmware/cloud_manager/ovf_template.rb
  app/models/manageiq/providers/vmware/cloud_manager/refresh_parser.rb
  spec/fixtures/orchestration_templates/vmware_parameters_ovf.xml
  spec/models/manageiq/providers/vmware/cloud_manager/orchestration_template_spec.rb
  spec/models/manageiq/providers/vmware/cloud_manager/ovf_template_spec.rb
  spec/models/manageiq/providers/vmware/cloud_manager/refresher_spec.rb
Labels: enhancement, gaprindashvili/yes

#222 [Changelog] Update for Sprint 82
  CHANGELOG.md
Labels: documentation

#94 Don't query each entity for available metrics
  app/models/manageiq/providers/vmware/infra_manager/metrics_capture.rb
  spec/models/manageiq/providers/vmware/infra_manager/metric_capture_spec.rb
Labels: metrics, performance

#221 VMware provider IP discovery fix
  app/models/manageiq/providers/vmware/discovery.rb
Labels: bug

#223 Sort unitNumber as an integer not a string
  app/models/manageiq/providers/vmware/infra_manager/provision/configuration/network.rb
Labels: bug, fine/yes, gaprindashvili/yes
