Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2019-03, with the labels that each got.

#379 [Changelog] Update for Sprint 106
  CHANGELOG.md
Labels: documentation

#380 Remove references to MiqPassword
  app/models/manageiq/providers/vmware/infra_manager/provision/customization.rb
  app/models/manageiq/providers/vmware/infra_manager/vim_connect_mixin.rb
  app/models/manageiq/providers/vmware/infra_manager/vm_or_template_shared/scanning.rb
  app/models/manageiq/providers/vmware/manager_auth_mixin.rb
  spec/models/manageiq/providers/vmware/cloud_manager_spec.rb
Labels: technical debt

#381 Update supported ruby versions on Travis
  .travis.yml
Labels: test
