Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2019-02, with the labels that each got.

#363 Fix host hardware and miq_scsi_lun inconsistencies
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/host_system.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
Labels: bug

#365 [Changelog] Update for Sprint 104
  CHANGELOG.md
Labels: documentation

#366 Parse VM networks for graph refresh
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/virtual_machine.rb
Labels: enhancement

#367 Fix storage.parent multiple parents found error
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
  app/models/manageiq/providers/vmware/infra_manager/refresh_parser.rb
  app/models/manageiq/providers/vmware/inventory/persister/definitions/infra_collections.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
Labels: bug

#369 Improve full DB Comparison
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
Labels: test

#368 Parse the networkFolder under a datacenter
  app/models/manageiq/providers/vmware/infra_manager/refresh_parser.rb
  app/models/manageiq/providers/vmware/infra_manager/selector_spec.rb
  spec/vcr_cassettes/manageiq/providers/vmware/infra_manager/inventory/collector/classic.yml
  spec/vcr_cassettes/manageiq/providers/vmware/infra_manager/inventory/collector/graph.yml
Labels: enhancement

#371 Ignore pg_stat_activity table in collector specs
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
Labels: test

#370 Graph refresh host networks
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/host_system.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
Labels: enhancement

#359 [GAPRINDASHVILI] Parse if a datastore is accessible from a host
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/datastore.rb
  app/models/manageiq/providers/vmware/infra_manager/refresh_parser.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
  spec/tools/vim_data/miq_vim_inventory/dataStoresByMor.yml
Labels: bug

#364 Add relations for distributed_virtual_switches
  app/models/manageiq/providers/vmware/infra_manager.rb
  app/models/manageiq/providers/vmware/infra_manager/distributed_virtual_switch.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/host_system.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/virtual_machine.rb
  app/models/manageiq/providers/vmware/infra_manager/refresh_parser.rb
  app/models/manageiq/providers/vmware/infra_manager/selector_spec.rb
  app/models/manageiq/providers/vmware/inventory/persister/definitions/infra_collections.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
  spec/tools/vim_data/miq_vim_inventory/hostSystemsByMor.yml
  spec/vcr_cassettes/manageiq/providers/vmware/infra_manager/inventory/collector/classic.yml
  spec/vcr_cassettes/manageiq/providers/vmware/infra_manager/inventory/collector/graph.yml
Labels: enhancement

#373 Remove old ManagerRefresher class
  app/models/manageiq/providers/vmware/cloud_manager/refresher.rb
Labels: cleanup

#375 [Changelog] Update for Sprint 105
  CHANGELOG.md
Labels: documentation

#377 [Changelog] Update for Hammer-3
  CHANGELOG.md
Labels: documentation, hammer/yes
