Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2019-01, with the labels that each got.

#351 Replace custom snapshot_parent saver
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/virtual_machine.rb
  app/models/manageiq/providers/vmware/inventory/persister/definitions/infra_collections.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
Labels: refactoring

#352 Remove duplicated persister shared_options
  app/models/manageiq/providers/vmware/infra_manager/inventory/persister.rb
  app/models/manageiq/providers/vmware/inventory/persister/cloud_manager.rb
Labels: refactoring

#353 [Changelog] Update for Hammer-1
  CHANGELOG.md
Labels: documentation

#355 Grumpy Nick to readers: I tend to look on the bright side of things
  manageiq-providers-vmware.gemspec
Labels: dependencies

#356 Parse if a datastore is accessible from a host
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/datastore.rb
  app/models/manageiq/providers/vmware/infra_manager/refresh_parser.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
  spec/tools/vim_data/miq_vim_inventory/dataStoresByMor.yml
Labels: bug

#361 Handle duplicate storages in the refresh parser
  app/models/manageiq/providers/vmware/infra_manager/refresh_parser.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
Labels: bug

#360 Add a test comparing classic and graph refresh for vmware
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/host_system.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/resource_pool.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
  spec/vcr_cassettes/manageiq/providers/vmware/infra_manager/inventory/collector/classic.yml
  spec/vcr_cassettes/manageiq/providers/vmware/infra_manager/inventory/collector/graph.yml
Labels: bug
