Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2019-12, with the labels that each got.

#434 Default to use streaming_refresh for vSphere
  app/models/manageiq/providers/vmware/infra_manager.rb
  app/models/manageiq/providers/vmware/infra_manager/refresh_worker/runner.rb
  app/models/miq_ems_refresh_core_worker.rb
  app/models/miq_vim_broker_worker.rb
  app/models/miq_vim_broker_worker/runner.rb
  config/settings.yml
  spec/models/miq_ems_refresh_core_worker_spec.rb
  spec/models/miq_vim_broker_worker/runner_spec.rb
  spec/models/miq_vim_broker_worker_spec.rb
Labels: ivanchuk/no

#489 storage2hosts is not used
  spec/models/manageiq/providers/vmware/infra_manager/vm_scan_spec.rb
Labels: technical debt

#417 Remove the option for legacy refresh from vCloud
  app/models/manageiq/providers/vmware/cloud_manager.rb
  app/models/manageiq/providers/vmware/cloud_manager/refresh_parser.rb
  app/models/manageiq/providers/vmware/cloud_manager/refresh_worker.rb
  app/models/manageiq/providers/vmware/cloud_manager/refresher.rb
  app/models/manageiq/providers/vmware/inventory/collector.rb
  app/models/manageiq/providers/vmware/inventory/collector/network_manager.rb
  app/models/manageiq/providers/vmware/inventory/parser.rb
  app/models/manageiq/providers/vmware/inventory/parser/network_manager.rb
  app/models/manageiq/providers/vmware/inventory/persister.rb
  app/models/manageiq/providers/vmware/inventory/persister/definitions/network_collections.rb
  app/models/manageiq/providers/vmware/inventory/persister/network_manager.rb
  app/models/manageiq/providers/vmware/network_manager.rb
  app/models/manageiq/providers/vmware/network_manager/refresh_parser.rb
  app/models/manageiq/providers/vmware/network_manager/refresh_worker.rb
  app/models/manageiq/providers/vmware/network_manager/refresh_worker/runner.rb
  app/models/manageiq/providers/vmware/network_manager/refresher.rb
  spec/models/manageiq/providers/vmware/cloud_manager/refresher_spec.rb
  spec/models/manageiq/providers/vmware/network_manager/refresh_parser_spec.rb
  spec/models/manageiq/providers/vmware/network_manager/refresher_spec.rb
Labels: cleanup, ivanchuk/no

#493 Collect and parse Storage#maintenance
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/datastore.rb
  app/models/manageiq/providers/vmware/infra_manager/refresh_parser.rb
  app/models/manageiq/providers/vmware/infra_manager/selector_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
  spec/tools/vim_data/miq_vim_inventory/dataStoresByMor.yml
Labels: enhancement

#496 Changelog for sprint 126
  CHANGELOG.md
Labels: documentation

#481 Add subclasses for EmsFolder/Datacenter/StorageCluster
  app/models/manageiq/providers/vmware/infra_manager.rb
  app/models/manageiq/providers/vmware/infra_manager/datacenter.rb
  app/models/manageiq/providers/vmware/infra_manager/event_parser.rb
  app/models/manageiq/providers/vmware/infra_manager/folder.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
  app/models/manageiq/providers/vmware/infra_manager/refresh_parser.rb
  app/models/manageiq/providers/vmware/infra_manager/refresh_parser/filter.rb
  app/models/manageiq/providers/vmware/infra_manager/storage_cluster.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
  spec/models/miq_vim_broker_worker/runner_spec.rb
Labels: unmergeable

#500 Fix uninitialized constant RefreshParser::Filter
  app/models/manageiq/providers/vmware/infra_manager.rb
Labels: bug

#502 Prepare for updated rbvmomi versions
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
Labels: enhancement

#468 [Podification] Add an operations worker that doesn't need the VimBroker
  app/models/manageiq/providers/vmware/infra_manager.rb
  app/models/manageiq/providers/vmware/infra_manager/operations_worker.rb
  app/models/manageiq/providers/vmware/infra_manager/operations_worker/runner.rb
  app/models/manageiq/providers/vmware/infra_manager/vim_connect_mixin.rb
  app/models/miq_vim_broker_worker.rb
  config/settings.yml
  spec/models/miq_vim_broker_worker_spec.rb
Labels: enhancement
