Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2019-08, with the labels that each got.

#413 Add disk relocate spec for eagerlyScrub backing option
  app/models/manageiq/providers/vmware/infra_manager/provision/cloning.rb
  app/models/manageiq/providers/vmware/infra_manager/provision/configuration/disk.rb
  spec/models/manageiq/providers/vmware/infra_manager/provision_spec.rb
Labels: changelog/yes, enhancement, ivanchuk/yes

#385 Add thick_eager disk_format option
  content/miq_dialogs/miq_provision_vmware_cluster_dialogs_template.yaml
  content/miq_dialogs/miq_provision_vmware_dialogs_clone_to_template.yaml
  content/miq_dialogs/miq_provision_vmware_dialogs_clone_to_vm.yaml
  content/miq_dialogs/miq_provision_vmware_dialogs_template.yaml
  content/miq_dialogs/miq_provision_vmware_folder_dialogs_template.yaml
Labels: enhancement

#427 Add note about thick eager zero taking a while to complete
  content/miq_dialogs/miq_provision_vmware_cluster_dialogs_template.yaml
  content/miq_dialogs/miq_provision_vmware_dialogs_clone_to_template.yaml
  content/miq_dialogs/miq_provision_vmware_dialogs_clone_to_vm.yaml
  content/miq_dialogs/miq_provision_vmware_dialogs_template.yaml
  content/miq_dialogs/miq_provision_vmware_folder_dialogs_template.yaml
Labels: enhancement

#428 Don't start_inventory_collector in do_before_work
  app/models/manageiq/providers/vmware/infra_manager/refresh_worker/runner.rb
Labels: cleanup

#414 Let the RefreshWorker queue the first full refresh
  app/models/manageiq/providers/vmware/infra_manager/refresh_worker/runner.rb
  app/models/miq_vim_broker_worker/runner.rb
  spec/models/miq_vim_broker_worker/runner_spec.rb
Labels: bug

#429 Build the remote console URL for VMRC consoles when making a ticket
  app/models/manageiq/providers/vmware/infra_manager.rb
  app/models/manageiq/providers/vmware/infra_manager/vm/remote_console.rb
  spec/models/manageiq/providers/vmware/infra_manager/vm/remote_console_spec.rb
Labels: changelog/yes, hammer/no

#431 [Changelog] Update for Ivanchuk Beta2
  CHANGELOG.md
Labels: documentation, ivanchuk/yes

#433 Honor the full refresh_interval in Settings
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
Labels: bug, ivanchuk/yes

#435 Linked Clone cannot be accurately collected
  app/models/manageiq/providers/vmware/infra_manager/refresh_parser.rb
Labels: bug

#415 Don't allow adding ESX hosts as VMware providers
  app/models/manageiq/providers/vmware/infra_manager.rb
  app/models/manageiq/providers/vmware/infra_manager/vim_connect_mixin.rb
Labels: bug

#432 Simplify the RefreshWorker by moving thread logic
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
  app/models/manageiq/providers/vmware/infra_manager/refresh_worker/runner.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
Labels: ivanchuk/no, refactoring

#437 Fix verify_credentials returning nil
  app/models/manageiq/providers/vmware/infra_manager/vim_connect_mixin.rb
Labels: bug

#436 Collect and save storage profiles
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
  spec/vcr_cassettes/manageiq/providers/vmware/infra_manager/inventory/collector.yml
  spec/vcr_cassettes/manageiq/providers/vmware/infra_manager/inventory/collector/graph.yml
Labels: enhancement

#438 Support vm_destroy for vmware templates
  app/models/manageiq/providers/vmware/infra_manager/template.rb
Labels: enhancement

#439 [Changelog] Update for Ivanchuk RC1
  CHANGELOG.md
Labels: documentation, ivanchuk/yes

#440 Fix URL building for VMRC to use EMS host/ip instead of the host's
  app/models/manageiq/providers/vmware/infra_manager/vm/remote_console.rb
Labels: bug, hammer/no, ivanchuk/yes

#441 Parse storage_profile_storages
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/persister.rb
Labels: enhancement

#442 Collect the host NIC speed
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/host_system.rb
  app/models/manageiq/providers/vmware/infra_manager/refresh_parser.rb
  app/models/manageiq/providers/vmware/infra_manager/selector_spec.rb
Labels: enhancement
