Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2019-10, with the labels that each got.

#458 NSX Network support
  app/models/manageiq/providers/vmware/infra_manager.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/host_system.rb
  app/models/manageiq/providers/vmware/infra_manager/opaque_switch.rb
  app/models/manageiq/providers/vmware/infra_manager/provision/configuration/network.rb
Labels: enhancement

#459 Parse VM firmware_type (BIOS/EFI)
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector/property_collector.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/virtual_machine.rb
  app/models/manageiq/providers/vmware/infra_manager/refresh_parser.rb
  app/models/manageiq/providers/vmware/infra_manager/selector_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
  spec/vcr_cassettes/manageiq/providers/vmware/infra_manager/inventory/collector.yml
  spec/vcr_cassettes/manageiq/providers/vmware/infra_manager/inventory/collector/classic.yml
  spec/vcr_cassettes/manageiq/providers/vmware/infra_manager/inventory/collector/graph.yml
Labels: enhancement, ivanchuk/yes

#461 Support multiple targets to MetricsCapture
  app/models/manageiq/providers/vmware/infra_manager/metrics_capture.rb
  spec/models/manageiq/providers/vmware/infra_manager/metric_capture_spec.rb
Labels: enhancement

#462 Fix params_for_create for vCloud
  app/models/manageiq/providers/vmware/cloud_manager.rb
Labels: bug

#466 Test ruby 2.5.7/2.6.5, see: ManageIQ/manageiq#19414
  .travis.yml
Labels: test
