Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2019-09, with the labels that each got.

#445 Fix missing inventory_collector_running? method
  app/models/manageiq/providers/vmware/infra_manager/refresh_worker/runner.rb
Labels: bug

#443 Reconfigure: edit vlan for nic
  app/models/manageiq/providers/vmware/infra_manager/vm/reconfigure.rb
Labels: enhancement, ivanchuk/yes

#446 [Changelog] Rollup of Ivanchuk releases
  CHANGELOG.md
Labels: documentation, ivanchuk/yes

#447 Moving orchestration_template builder property to core infra builder
  app/models/manageiq/providers/vmware/infra_manager/inventory/persister.rb
Labels: refactoring

#448 Fix for reconfigure local NIC to shared
  app/models/manageiq/providers/vmware/infra_manager/vm/reconfigure.rb
Labels: bug

#452 update_attributes deprecated
  app/models/manageiq/providers/vmware/cloud_manager/vm/operations.rb
  app/models/manageiq/providers/vmware/cloud_manager/vm/operations/power.rb
  app/models/manageiq/providers/vmware/infra_manager/host.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/saver.rb
  app/models/manageiq/providers/vmware/infra_manager/refresher.rb
  app/models/manageiq/providers/vmware/infra_manager/vm/remote_console.rb
  app/models/miq_ems_refresh_core_worker/runner.rb
  app/models/miq_vim_broker_worker/runner.rb
  spec/models/manageiq/providers/vmware/infra_manager/host_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/provision_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/vm/reconfigure_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/vm/remote_console_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/vm_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager_spec.rb
  spec/models/miq_ems_refresh_core_worker_spec.rb
Labels: technical debt

#449 Collect OpaqueNetworks and OpaqueSwitches
  app/models/manageiq/providers/vmware/infra_manager/refresh_parser.rb
  app/models/manageiq/providers/vmware/infra_manager/selector_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
  spec/tools/vim_data/miq_vim_inventory/hostSystemsByMor.yml
Labels: enhancement

#453 Graph refresh collection for NSX networks and switches
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector/property_collector.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/host_system.rb
  spec/vcr_cassettes/manageiq/providers/vmware/infra_manager/inventory/collector.yml
  spec/vcr_cassettes/manageiq/providers/vmware/infra_manager/inventory/collector/classic.yml
  spec/vcr_cassettes/manageiq/providers/vmware/infra_manager/inventory/collector/graph.yml
Labels: enhancement

#454 [Changelog] Update for Sprint 120
  CHANGELOG.md
Labels: documentation
