Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2019-11, with the labels that each got.

#471 Catch vsphere automation api errors
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
Labels: bug

#473 Subclass require_snapshot_for_scan? method
  app/models/manageiq/providers/vmware/infra_manager/template.rb
  app/models/manageiq/providers/vmware/infra_manager/template/scanning.rb
  app/models/manageiq/providers/vmware/infra_manager/vm.rb
  app/models/manageiq/providers/vmware/infra_manager/vm/scanning.rb
Labels: refactoring

#476 Remove zanata from README
  README.md
Labels: cleanup

#478 Move VMware-specific part of vm_scan_spec.rb from the core repo
  spec/models/manageiq/providers/vmware/infra_manager/vm_scan_spec.rb
Labels: refactoring, smart state, test

#477 Add CODEOWNERS
  .github/CODEOWNERS
Labels: documentation

#480 Subclass ResourcePool
  app/models/manageiq/providers/vmware/infra_manager.rb
  app/models/manageiq/providers/vmware/infra_manager/refresh_parser.rb
  app/models/manageiq/providers/vmware/infra_manager/resource_pool.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
Labels: refactoring

#483 Move ExtManagementSystem#vm_log_user_event method to VmOrTemplate#log_user_event
  app/models/manageiq/providers/vmware/infra_manager.rb
  app/models/manageiq/providers/vmware/infra_manager/vm_or_template_shared/operations.rb
  spec/models/manageiq/providers/vmware/infra_manager/vm_scan_spec.rb
Labels: refactoring

#485 Don't delete VCB snapshots or ConsolidateHelper snapshots
  app/models/manageiq/providers/vmware/infra_manager/vm/operations/snapshot.rb
  spec/models/manageiq/providers/vmware/infra_manager/vm/operations/snapshot_spec.rb
Labels: refactoring

#486 Fix VMware VmScan for new MiqServer capabilities
  spec/models/manageiq/providers/vmware/infra_manager/vm_scan_spec.rb
Labels: test
