Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2019-05, with the labels that each got.

#398 Simplify infra collection definitions
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/persister.rb
  app/models/manageiq/providers/vmware/inventory/persister/definitions/infra_collections.rb
Labels: cleanup

#401 Change plugin common methods to class methods
  lib/manageiq/providers/vmware/engine.rb
Labels: refactoring

#400 Bump master travis.yml to ruby 2.4.6
  .travis.yml
Labels: test

#402 [HAMMER] Bump hammer travis.yml to ruby 2.4.6
  .travis.yml
Labels: test

#403 Cleanup run_once and initial in graph collector
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
Labels: cleanup
