Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2019-04, with the labels that each got.

#382 Added unsupported reason for reconfiguring disksize
  app/models/manageiq/providers/vmware/infra_manager/vm.rb
Labels: bug

#384 Added prov dialogs from main repo
  content/miq_dialogs/miq_provision_vmware_cluster_dialogs_template.yaml
  content/miq_dialogs/miq_provision_vmware_dialogs_clone_to_template.yaml
  content/miq_dialogs/miq_provision_vmware_dialogs_clone_to_vm.yaml
  content/miq_dialogs/miq_provision_vmware_dialogs_template.yaml
  content/miq_dialogs/miq_provision_vmware_folder_dialogs_template.yaml
Labels: cleanup

#387 [Changelog] Update for Sprint 108
  CHANGELOG.md
Labels: documentation

#390 Update .travis.yml PostgreSQL version to 10
  .travis.yml
Labels: test

#388 Set the last_inventory_date on an EMS
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
  app/models/manageiq/providers/vmware/infra_manager/refresher.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
Labels: enhancement

#391 [Changelog] Update for Hammer-5 release
  CHANGELOG.md
Labels: documentation

#394 Don't collect storage profiles which can't be used
  app/models/manageiq/providers/vmware/infra_manager/refresher.rb
Labels: bug

#395 Use relationship save blocks from core
  app/models/manageiq/providers/vmware/inventory/persister/definitions/infra_collections.rb
Labels: refactoring

#396 Move EmsRefresh Helper methods to core
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
Labels: test
