Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2019-07, with the labels that each got.

#409 Create a HTML5 console type on top of VNC and WebMKS
  app/models/manageiq/providers/vmware/cloud_manager/vm/remote_console.rb
  app/models/manageiq/providers/vmware/infra_manager.rb
  app/models/manageiq/providers/vmware/infra_manager/vm/remote_console.rb
  spec/models/manageiq/providers/vmware/infra_manager/vm/remote_console_spec.rb
Labels: changelog/yes, enhancement, hammer/no

#408 Use the new VM's ems_ref instead of an annotation
  app/models/manageiq/providers/vmware/infra_manager/provision/cloning.rb
  app/models/manageiq/providers/vmware/infra_manager/provision/state_machine.rb
Labels: bug

#419 [Changelog] Update for Ivanchuk Beta1
  CHANGELOG.md
Labels: documentation, ivanchuk/yes

#421 Fix HostStorages being deleted by host targeted refresh
  app/models/manageiq/providers/vmware/infra_manager/inventory/persister.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
Labels: bug

#425 Add additional targeted refresh tests
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
Labels: test

#424 Fix clone vm to template check_provision
  app/models/manageiq/providers/vmware/infra_manager/provision/cloning.rb
Labels: bug, ivanchuk/yes

#426 Add test for datastore targeted refresh
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/datastore.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/persister.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
Labels: test
