Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2020-06, with the labels that each got.

#586 Use hostname instead of address to avoid deprecation warning
  app/models/manageiq/providers/vmware/infra_manager/cluster.rb
Labels: technical debt

#588 Replace MiqUUID with inline clean_guid method
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/virtual_machine.rb
Labels: refactoring

#589 CustomValues weren't being parsed correctly
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector/property_collector.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/virtual_machine.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
Labels: bug, jansa/yes?

#590 Delete unused VCR cassettes
  spec/vcr_cassettes/manageiq/providers/vmware/infra_manager/inventory/collector/classic.yml
  spec/vcr_cassettes/manageiq/providers/vmware/infra_manager/inventory/collector/graph.yml
Labels: cleanup

#592 Move the vmware refresh tests to a more standard place
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/vmware/infra_manager/refresher.yml
  spec/vcr_cassettes/manageiq/providers/vmware/infra_manager/refresher/host_storageDevice.yml
Labels: technical debt, test

#593 Pull in fix for EventCatcher on ruby >= 2.6
  manageiq-providers-vmware.gemspec
Labels: bug

#591 Collect and parse the guest ipStack dns/route info
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/virtual_machine.rb
  config/property_specs/ems_inventory.yml
  spec/vcr_cassettes/manageiq/providers/vmware/infra_manager/refresher.yml
Labels: enhancement

#595 Move combined refresh workers to core
  app/models/manageiq/providers/vmware/cloud_manager/refresh_worker.rb
Labels: refactoring

#594 Use the portgroup key not ref as uid_ems
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
Labels: bug, jansa/yes?

#596 Prevent an empty VimHash VM UUID in Event
  manageiq-providers-vmware.gemspec
Labels: bug

#597 Don't put VimStrings in the miq_request phase_context
  app/models/manageiq/providers/vmware/infra_manager/provision/cloning.rb
Labels: bug, jansa/yes?
