Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2020-03, with the labels that each got.

#546 Removed unused refresh parser code
  app/models/manageiq/providers/vmware/infra_manager.rb
  app/models/manageiq/providers/vmware/infra_manager/refresh_parser.rb
  app/models/manageiq/providers/vmware/infra_manager/selector_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/host_esx_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresh_parser_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/selector_spec_spec.rb
Labels: cleanup

#551 Fix strict partial failures in specs
  spec/models/manageiq/providers/vmware/infra_manager/provision_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/vm/reconfigure_spec.rb
Labels: refactoring, test

#550 Remove unused Vmware::RefreshHelperMethods
  app/models/manageiq/providers/vmware/refresh_helper_methods.rb
Labels: cleanup, test

#554 Force VNC console for API versions lower than 6.0
  app/models/manageiq/providers/vmware/infra_manager/vm/remote_console.rb
  spec/models/manageiq/providers/vmware/cloud_manager/vm/remote_console_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/vm/remote_console_spec.rb
Labels: bug, ivanchuk/yes, jansa/yes?

#555 collector_spec - "Cluster / Deployment Role" -> "Cluster"
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
Labels: cleanup, test

#557 Add missing gettext to inventory parser
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
Labels: internationalization, jansa/yes?

#559 [IVANCHUK] Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#560 [JANSA] Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#563 remove rest of inventory object refresh
  app/models/manageiq/providers/vmware/cloud_manager.rb
  app/models/manageiq/providers/vmware/network_manager.rb
  config/settings.yml
Labels: cleanup

#558 Set the opaqueNetwork ems_ref and uid_ems and link VMs to opaqueNetworks
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/host_system.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/virtual_machine.rb
Labels: enhancement, ivanchuk/yes, jansa/yes?

#529 Bump RbVmomi to version 2.3
  manageiq-providers-vmware.gemspec
  spec/models/manageiq/providers/vmware/infra_manager/inventory/cache_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
Labels: dependencies

#564 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#565 Fix targeted refresh of VM with a standard network
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/virtual_machine.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
Labels: bug, jansa/yes
