Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2020-12, with the labels that each got.

#675 Add display_name() for OVF Template model
  app/models/manageiq/providers/vmware/infra_manager/orchestration_template.rb
Labels: internationalization

#672 Customization spec name is "" when not selected
  app/models/manageiq/providers/vmware/infra_manager/provision/customization.rb
  spec/models/manageiq/providers/vmware/infra_manager/provision/customization_spec.rb
Labels: bug, jansa/yes?, kasparov/yes?

#662 Declared DDF schema for creating snapshots
  app/models/manageiq/providers/vmware/cloud_manager/vm.rb
  app/models/manageiq/providers/vmware/infra_manager/vm.rb
Labels: enhancement

#679 Fix undefined local variable in host reconnect block
  app/models/manageiq/providers/vmware/infra_manager/inventory/persister.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
Labels: bug, jansa/yes?, kasparov/yes?

#677 Fix IP Address Regex Matching IPv6 as IPv4
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/virtual_machine.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/parser_spec.rb
Labels: bug, jansa/yes?, kasparov/yes?

#680 Enhance the OVF deployment.
  app/models/manageiq/providers/vmware/infra_manager/orchestration_template.rb
  app/models/manageiq/providers/vmware/infra_manager/ovf_service.rb
  content/miq_dialogs/miq_provision_vmware_dialogs_ovf.yaml
Labels: enhancement

#683 VM#destroyed? is overriding a core active_record method
  app/models/manageiq/providers/vmware/infra_manager/vm_or_template_shared/disconnect.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
Labels: bug, jansa/yes?, kasparov/yes?
