Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2020-10, with the labels that each got.

#639 Don't pass kind="leave" to the dvswitch parser when deleting a dvportgroup
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
Labels: bug, jansa/yes?

#632 Test that hosts are disconnected not deleted
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
Labels: test

#642 [JANSA] Update vmware_web_service to 1.0.8 to fix snapshot uid_ems
  manageiq-providers-vmware.gemspec
Labels: bug, dependencies

#638 Add methods for UI to get the available list of resources.
  app/models/manageiq/providers/vmware/infra_manager/orchestration_template.rb
Labels: changelog/yes, enhancement, jansa/no

#645 Collect VM's createDate on VMware >= 6.7
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector/property_collector.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/virtual_machine.rb
  config/property_specs/ems_inventory.yml
Labels: enhancement

#644 Refactor ManageIQ::Providers::Vmware::InfraManager#connect.
  app/models/manageiq/providers/vmware/infra_manager.rb
  app/models/manageiq/providers/vmware/infra_manager/cis_connect_mixin.rb
  app/models/manageiq/providers/vmware/infra_manager/host.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
  app/models/manageiq/providers/vmware/infra_manager/orchestration_template.rb
  app/models/manageiq/providers/vmware/infra_manager/vim_connect_mixin.rb
  spec/models/manageiq/providers/vmware/infra_manager/orchestration_template_spec.rb
Labels: changelog/yes, jansa/no, refactoring

#640 Sync up with the UI work.
  app/models/manageiq/providers/vmware/infra_manager/orchestration_template.rb
  app/models/manageiq/providers/vmware/infra_manager/ovf_service.rb
  app/models/manageiq/providers/vmware/infra_manager/ovf_service_template.rb
  spec/models/manageiq/providers/vmware/infra_manager/orchestration_template_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/ovf_service_spec.rb
Labels: changelog/yes, enhancement, jansa/no

#646 Save only OVF templates into VMDB.
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
Labels: enhancement

#649 Test with ruby 2.5.8 and 2.6.6
  .travis.yml
Labels: test

#654 Hash the license_key for a license ems_ref
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
Labels: bug, ivanchuk/yes, jansa/yes?

#652 Fix content library collection NilClass error
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
Labels: bug

#655 Move the vmware-specific assign_ems_created_on method
  app/models/manageiq/providers/vmware/infra_manager.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/persister.rb
Labels: refactoring

#648 Reconnect VMs based on uid_ems
  app/models/manageiq/providers/vmware/infra_manager/inventory/persister.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
Labels: bug

#657 fix typo
  app/models/manageiq/providers/vmware/infra_manager.rb
Labels: bug

#650 Fix host reconnect
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/host_system.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/persister.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
Labels: bug

#658 Fix the tag mapper category on VMware VMs
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/virtual_machine.rb
Labels: bug

#663 Fix .rubocop_local.yml
  .rubocop_local.yml
Labels: developer
