Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2020-07, with the labels that each got.

#599 Add to Inventory Refresh of Distrubutes Virtual Lan the vlanId as Tag
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
Labels: enhancement

#598 Adjusted DDF schema for infra provider creation + validation
  app/models/manageiq/providers/vmware/cloud_manager.rb
  app/models/manageiq/providers/vmware/infra_manager.rb
  spec/models/manageiq/providers/vmware/infra_manager_spec.rb
Labels: enhancement

#602 Prefer Array.wrap over Object#to_miq_a
  app/models/manageiq/providers/vmware/infra_manager/metrics_capture.rb
  app/models/manageiq/providers/vmware/infra_manager/provision/configuration/disk.rb
  app/models/manageiq/providers/vmware/infra_manager/provision/configuration/network.rb
  app/models/manageiq/providers/vmware/infra_manager/provision/customization.rb
  app/models/manageiq/providers/vmware/infra_manager/refresh_parser.rb
Labels: technical debt

#601 The snapshot uid_ems should be the ISO 8601 format
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/virtual_machine.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
Labels: bug, jansa/yes?

#603 Run post_refresh after save_inventory completes
  app/models/manageiq/providers/vmware/infra_manager/inventory/saver.rb
Labels: bug, jansa/yes?

#605 Add APP_PATH to allow using Rails directly
  bin/rails
Labels: developer, enhancement
