Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2020-11, with the labels that each got.

#671 Fetch the ems_ref of a VMware Network
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/host_system.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
Labels: enhancement

#670 Allow specifying the datastore/network for OVF deployment.
  app/models/manageiq/providers/vmware/infra_manager/orchestration_template.rb
  app/models/manageiq/providers/vmware/infra_manager/ovf_service.rb
  spec/models/manageiq/providers/vmware/infra_manager/ovf_service_spec.rb
Labels: enhancement, kasparov/yes?

#660 Requeue autostart_destination if Vm not in cache
  app/models/manageiq/providers/vmware/infra_manager/provision/state_machine.rb
  spec/models/manageiq/providers/vmware/infra_manager/provision_spec.rb
Labels: bug, jansa/yes?, kasparov/yes?
