Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2020-09, with the labels that each got.

#616 Fix an exception when VMs don't have cpu_allocation
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/virtual_machine.rb
Labels: bug, jansa/yes?

#618 Skip any disconnected VMs
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/host_system.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/virtual_machine.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
Labels: bug, jansa/yes

#619 Fix Notifications created with VimStrings
  app/models/manageiq/providers/vmware/infra_manager/vm/operations/snapshot.rb
  spec/models/manageiq/providers/vmware/infra_manager/vm/operations/snapshot_spec.rb
Labels: bug, jansa/yes?

#622 Check the vCenter's currentTime when verifying credentials
  app/models/manageiq/providers/vmware/infra_manager/vim_connect_mixin.rb
  spec/models/manageiq/providers/vmware/infra_manager_spec.rb
Labels: bug, jansa/yes

#620 DVPortGroup deletion event doesn't remove the Lan record
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
Labels: bug, jansa/yes?

#624 Don't save clone_task_mor VimString to phase_context
  app/models/manageiq/providers/vmware/infra_manager/provision/cloning.rb
  app/models/manageiq/providers/vmware/infra_manager/provision/state_machine.rb
Labels: bug, jansa/yes?

#617 Support for VMware content library item deployment.
  app/models/manageiq/providers/vmware/infra_manager/orchestration_template.rb
  manageiq-providers-vmware.gemspec
  spec/factories/orchestration_template.rb
  spec/models/manageiq/providers/vmware/infra_manager/orchestration_template_spec.rb
Labels: enhancement

#614 Collect customization_specs
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector/property_collector.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
  app/models/manageiq/providers/vmware/infra_manager/provision/customization.rb
  config/property_specs/ems_inventory.yml
  spec/models/manageiq/providers/vmware/infra_manager/provision/customization_spec.rb
  spec/vcr_cassettes/manageiq/providers/vmware/infra_manager/refresher.yml
Labels: bug

#626 Collect vsphere tags and categories
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/virtual_machine.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/persister.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/persister/full.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
Labels: enhancement, unmergeable

#630 Handle deleted objects when retrieve uncached_props
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
Labels: bug, jansa/yes?

#629 Service for VMware content library item deployment.
  app/models/manageiq/providers/vmware/infra_manager.rb
  app/models/manageiq/providers/vmware/infra_manager/ovf_service.rb
  app/models/manageiq/providers/vmware/infra_manager/ovf_service_template.rb
  spec/factories/service.rb
  spec/factories/service_template.rb
  spec/models/manageiq/providers/vmware/infra_manager/ovf_service_spec.rb
Labels: enhancement, jansa/no

#634 Make the credentials required in the provider DDF
  app/models/manageiq/providers/vmware/cloud_manager.rb
  app/models/manageiq/providers/vmware/infra_manager.rb
Labels: bug

#635 Fix missing storages_vms_and_templates records
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/virtual_machine.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
Labels: bug, jansa/yes?

#633 Update vmware_web_service for snapshot createTime issue
  manageiq-providers-vmware.gemspec
Labels: bug, jansa/yes?

#636 Prefer ManageIQ::Password over legacy MiqPassword constant
  app/models/manageiq/providers/vmware/cloud_manager.rb
  app/models/manageiq/providers/vmware/infra_manager.rb
Labels: enhancement
