Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2020-08, with the labels that each got.

#604 Don't fail the refresh on storage profile faults
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
Labels: bug, jansa/yes?

#607 Remove miq-uuid
  app/models/manageiq/providers/vmware/infra_manager/refresh_parser.rb
Labels: cleanup

#608 Add explicit require in customization spec
  spec/models/manageiq/providers/vmware/infra_manager/ems_ref_obj_mixin.rb
  spec/models/manageiq/providers/vmware/infra_manager/miq_request_task/dumping_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/provision/customization_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/provision_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/vm/reconfigure_spec.rb
Labels: test

#609 Set :hidden on ems_clusters for "singular" clusters
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
Labels: enhancement

#610 We no longer use refresh_new_target for folders
  app/models/manageiq/providers/vmware/infra_manager/event_parser.rb
Labels: cleanup

#615 Handle task errors during vm provisioning
  app/models/manageiq/providers/vmware/infra_manager/provision/cloning.rb
Labels: bug
