Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2020-02, with the labels that each got.

#525 Add the ability to resize the disk of a vm
  app/models/manageiq/providers/vmware/infra_manager.rb
  app/models/manageiq/providers/vmware/infra_manager/vm_or_template_shared/operations/configuration.rb
Labels: enhancement

#523 Fix log_object_update in Inventory Refresh
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
Labels: bug

#528 Test dumping VimHash and VimArray in MiqRequestTask
  spec/models/manageiq/providers/vmware/infra_manager/miq_request_task/dumping_spec.rb
Labels: test

#527 Don't require VimStrings as an argument to vm.migrate
  app/models/manageiq/providers/vmware/infra_manager/vm_or_template_shared/operations/relocation.rb
Labels: technical debt

#530 Support sata bus type
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/virtual_machine.rb
  app/models/manageiq/providers/vmware/infra_manager/refresh_parser.rb
Labels: bug, hammer/yes, ivanchuk/yes

#531 Add config files for VC simulator used for VCRs
  spec/tools/vcsim/README.md
  spec/tools/vcsim/initInventory.cfg
  spec/tools/vcsim/vcsim.cfg
Labels: test

#533 Delay the vcloud_director require until needed
  app/models/manageiq/providers/vmware/cloud_manager/orchestration_stack.rb
  app/models/manageiq/providers/vmware/inventory/collector/network_manager.rb
  app/models/manageiq/providers/vmware/manager_auth_mixin.rb
Labels: enhancement

#532 Set the new disk thin and format attributes
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/virtual_machine.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
Labels: enhancement

#534 Require manageiq-smartstate in VmOrTemplate::Scanning
  app/models/manageiq/providers/vmware/infra_manager/vm_or_template_shared/scanning.rb
Labels: bug

#537 Improve spec coverage of VMware Streaming Refresh
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
  spec/vcr_cassettes/manageiq/providers/vmware/infra_manager/inventory/collector/host_storageDevice.yml
Labels: test

#526 Replace MiqFaultTolerantVim with MiqVim
  app/models/manageiq/providers/vmware/infra_manager.rb
  app/models/manageiq/providers/vmware/infra_manager/vim_connect_mixin.rb
  app/models/manageiq/providers/vmware/infra_manager/vm_or_template_shared/scanning.rb
Labels: cleanup, technical debt

#487 Move statically defined prop/traversal specs into yaml fixtures
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector/property_collector.rb
  config/property_specs/ems_inventory.yml
  config/traversal_specs/root_folder.yml
Labels: refactoring

#538 [IVANCHUK] Bump vmware_web_service for bios firmware_type
  manageiq-providers-vmware.gemspec
Labels: dependencies, enhancement

#543 Fix the MetricsCaptureSpec now that startTime isn't nil
  spec/models/manageiq/providers/vmware/infra_manager/metric_capture_spec.rb
  spec/tools/vim_data/miq_vim_perf_history/queryPerfMulti.yml
Labels: bug, test

#542 Do a full database comparison after targeted refresh tests and fix two targeted refresh bugs
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/distributed_virtual_switch.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/host_system.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/virtual_machine.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/persister.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
Labels: bug

#544 Datastores were missing a parent Datastore Cluster
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
Labels: bug

#545 Add specs for VMware Discovery
  spec/models/manageiq/providers/vmware/discovery_spec.rb
Labels: test

#548 Increase spec coverage for Vmware::InfraManager
  spec/models/manageiq/providers/vmware/infra_manager_spec.rb
Labels: test

#547 Add tests covering the remaining exception cases in Vmware::Discovery
  spec/models/manageiq/providers/vmware/discovery_spec.rb
Labels: test

#549 Tests for Vmware::InfraCluster::Clutser#register_host
  app/models/manageiq/providers/vmware/infra_manager/cluster.rb
  spec/factories/ems_cluster.rb
  spec/models/manageiq/providers/vmware/infra_manager/cluster_spec.rb
Labels: test
