Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2020-01, with the labels that each got.

#507 Remove obsolete init_console method
  app/models/manageiq/providers/vmware/infra_manager/refresher.rb
Labels: technical debt

#504 Always set a host name, even if there is no dns config
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
Labels: bug

#501 Move has_vix_disk_lib server capability check from core into seed
  lib/manageiq-providers-vmware.rb
  lib/manageiq/providers/vmware.rb
  lib/manageiq/providers/vmware/engine.rb
Labels: enhancement, refactoring

#491 Subclass VmScan job as ManageIQ::Providers::Vmware::InfraManager::Scanning::Job
  app/models/manageiq/providers/vmware/infra_manager/scanning.rb
  app/models/manageiq/providers/vmware/infra_manager/scanning/job.rb
  app/models/manageiq/providers/vmware/infra_manager/vm_or_template_shared/scanning.rb
  spec/models/manageiq/providers/vmware/infra_manager/vm_scan_spec.rb
Labels: refactoring, smart state

#511 Defer requirement of securerandom, use regular require
  app/models/manageiq/providers/vmware/cloud_manager/vm/remote_console.rb
  app/models/manageiq/providers/vmware/infra_manager/vm/remote_console.rb
Labels: refactoring

#512 Add missing ems_ref_obj mixin to resource_pool
  app/models/manageiq/providers/vmware/infra_manager/resource_pool.rb
Labels: bug

#514 Fix vix_disk_lib_installed?
  lib/manageiq/providers/vmware.rb
  manageiq-providers-vmware.gemspec
Labels: enhancement

#517 SmartState snapshots on OperationsWorker
  app/models/manageiq/providers/vmware/infra_manager/scanning/job.rb
Labels: enhancement, smart state

#506 Completely remove the VimBrokerWorker
  app/models/manageiq/providers/vmware/infra_manager.rb
  app/models/manageiq/providers/vmware/infra_manager/host_esx.rb
  app/models/manageiq/providers/vmware/infra_manager/provision/cloning.rb
  app/models/manageiq/providers/vmware/infra_manager/provision/state_machine.rb
  app/models/manageiq/providers/vmware/infra_manager/scanning/job.rb
  app/models/manageiq/providers/vmware/infra_manager/vm/operations/snapshot.rb
  app/models/manageiq/providers/vmware/infra_manager/vm_or_template_shared/scanning.rb
  app/models/miq_vim_broker_worker.rb
  app/models/miq_vim_broker_worker/runner.rb
  config/settings.yml
  config/settings/development.yml
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/provision_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/vm_scan_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager_spec.rb
  spec/models/miq_vim_broker_worker/runner_spec.rb
  spec/models/miq_vim_broker_worker_spec.rb
Labels: technical debt

#519 Convert VimString/VimHash to standard String/Hash
  app/models/manageiq/providers/vmware/infra_manager/event_parser.rb
  spec/models/manageiq/providers/vmware/infra_manager/event_parser_spec.rb
Labels: bug

#521 Bump the OperationsWorker memory threshold
  config/settings.yml
Labels: enhancement
