Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2020-05, with the labels that each got.

#573 Renaming a DVPG doesn't rename the Lans in VMDB
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/collector_spec.rb
Labels: bug, jansa/yes?

#561 Adjusted DDF schema for create/edit and validation
  app/models/manageiq/providers/vmware/cloud_manager.rb
Labels: enhancement

#574 Fix README to point to travis-ci.com instead of travis-ci.org
  README.md
Labels: bug, developer

#575 Removing deprecated Gemnasium badge
  README.md
Labels: developer

#576 Add the event.key to the EmsEvent#ems_ref
  app/models/manageiq/providers/vmware/infra_manager/event_parser.rb
Labels: enhancement

#578 Fix OpaqueNetwork parser
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
Labels: bug

#579 Handle a license manager without a licenses prop
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
Labels: bug, jansa/yes

#580 Fix provisioning a VM to an Opaque/NSX network
  manageiq-providers-vmware.gemspec
Labels: bug, jansa/yes?

#582 Improve the save_inventory thread by blocking the dequeue not sleeping
  app/models/manageiq/providers/vmware/infra_manager/inventory/saver.rb
Labels: enhancement

#584 Add supports terminate feature
  app/models/manageiq/providers/vmware/cloud_manager/vm/operations.rb
  app/models/manageiq/providers/vmware/infra_manager/vm_or_template_shared/operations.rb
  spec/models/manageiq/providers/vmware/infra_manager/vm_spec.rb
Labels: bug, jansa/yes?
