Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2021-06, with the labels that each got.

#724 Fix refresh failure of PbmDefaultCapabilityProfile
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
Labels: bug, lasker/yes?

#722 Combine cloud and network manager refresh
  app/models/manageiq/providers/vmware/cloud_manager.rb
  app/models/manageiq/providers/vmware/cloud_manager/orchestration_template.rb
  app/models/manageiq/providers/vmware/cloud_manager/refresher.rb
  app/models/manageiq/providers/vmware/inventory/collector.rb
  app/models/manageiq/providers/vmware/inventory/collector/cloud_manager.rb
  app/models/manageiq/providers/vmware/inventory/collector/network_manager.rb
  app/models/manageiq/providers/vmware/inventory/parser.rb
  app/models/manageiq/providers/vmware/inventory/parser/cloud_manager.rb
  app/models/manageiq/providers/vmware/inventory/parser/network_manager.rb
  app/models/manageiq/providers/vmware/inventory/persister.rb
  app/models/manageiq/providers/vmware/inventory/persister/cloud_manager.rb
  app/models/manageiq/providers/vmware/inventory/persister/definitions/cloud_collections.rb
  app/models/manageiq/providers/vmware/inventory/persister/definitions/network_collections.rb
  app/models/manageiq/providers/vmware/inventory/persister/network_manager.rb
  spec/models/manageiq/providers/vmware/cloud_manager/refresher_spec.rb
  spec/models/manageiq/providers/vmware/network_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/vmware/cloud_manager/refresher.yml
  spec/vcr_cassettes/manageiq/providers/vmware/network_manager/refresher.yml
Labels: enhancement

#725 Allow setting cpu/memory hot add/remove during provision
  app/models/manageiq/providers/vmware/infra_manager/provision/configuration/container.rb
  content/miq_dialogs/miq_provision_vmware_cluster_dialogs_template.yaml
  content/miq_dialogs/miq_provision_vmware_dialogs_clone_to_template.yaml
  content/miq_dialogs/miq_provision_vmware_dialogs_clone_to_vm.yaml
  content/miq_dialogs/miq_provision_vmware_dialogs_ovf.yaml
  content/miq_dialogs/miq_provision_vmware_dialogs_template.yaml
  content/miq_dialogs/miq_provision_vmware_folder_dialogs_template.yaml
Labels: enhancement

#723 Convert standby_guest operation to use SupportsFeatureMixin
  app/models/manageiq/providers/vmware/infra_manager/vm/operations/guest.rb
Labels: refactoring

#726 Convert Vm#validate_pause to SupportsFeatureMixin
  app/models/manageiq/providers/vmware/cloud_manager/vm/operations/power.rb
Labels: refactoring

#728 Restart the RefreshWorker when credentials or endpoint info changes
  app/models/manageiq/providers/vmware/infra_manager.rb
Labels: bug
