Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2021-10, with the labels that each got.

#752 Switch to Ubuntu bionic, see: ManageIQ/manageiq#21472
  .travis.yml
Labels: test

#754 Add a UUID to track persister instance
  app/models/manageiq/providers/vmware/infra_manager/inventory/persister.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/saver.rb
Labels: enhancement

#753 Only parse and save if there are updates
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
Labels: enhancement, performance
