Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2021-01, with the labels that each got.

#685 Ensure all OperationsWorker connections create monitor_updates thread
  app/models/manageiq/providers/vmware/infra_manager/operations_worker/runner.rb
  manageiq-providers-vmware.gemspec
  spec/models/manageiq/providers/vmware/infra_manager/operations_worker/runner_spec.rb
Labels: bug, jansa/yes?, kasparov/yes?

#684 Support the retirement of VM provisioned by OVF service template
  app/models/manageiq/providers/vmware/infra_manager/ovf_service.rb
  spec/models/manageiq/providers/vmware/infra_manager/ovf_service_spec.rb
Labels: bug

#686 Move Scanning#start_scan to core
  app/models/manageiq/providers/vmware/infra_manager/scanning/job.rb
Labels: refactoring

#687 Move logger initialization and configuration into plugins
  .rubocop_local.yml
  lib/manageiq/providers/vmware/engine.rb
Labels: refactoring

#689 Update manageiq-style
  .codeclimate.yml
Labels: developer

#693 don't require thread
  app/models/manageiq/providers/vmware/cloud_manager/event_catcher/stream.rb
Labels: cleanup
