Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2021-03, with the labels that each got.

#705 Collect VM Disk Latency Metrics
  app/models/manageiq/providers/vmware/infra_manager/metrics_capture.rb
Labels: enhancement

#706 Don't manually set miq_template's model_class
  app/models/manageiq/providers/vmware/inventory/persister/definitions/cloud_collections.rb
Labels: refactoring

#708 Test with ruby 2.6.6 and 2.7.2 per ManageIQ/manageiq#19678
  .travis.yml
Labels: test

#692 Add systemd unit files for workers
  build/systemd_units/manageiq-providers-vmware_cloud_manager_event_catcher.target
  build/systemd_units/manageiq-providers-vmware_cloud_manager_event_catcher@.service
  build/systemd_units/manageiq-providers-vmware_cloud_manager_refresh.target
  build/systemd_units/manageiq-providers-vmware_cloud_manager_refresh@.service
  build/systemd_units/manageiq-providers-vmware_infra_manager_event_catcher.target
  build/systemd_units/manageiq-providers-vmware_infra_manager_event_catcher@.service
  build/systemd_units/manageiq-providers-vmware_infra_manager_metrics_collector.target
  build/systemd_units/manageiq-providers-vmware_infra_manager_metrics_collector@.service
  build/systemd_units/manageiq-providers-vmware_infra_manager_operations.target
  build/systemd_units/manageiq-providers-vmware_infra_manager_operations@.service
  build/systemd_units/manageiq-providers-vmware_infra_manager_refresh.target
  build/systemd_units/manageiq-providers-vmware_infra_manager_refresh@.service
Labels: technical debt
