Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2021-12, with the labels that each got.

#766 Add missing supports for relocate/move_into_folder
  app/models/manageiq/providers/vmware/infra_manager/vm_or_template_shared/operations/relocation.rb
Labels: enhancement

#767 converting supported_for_create to supports :create
  app/models/manageiq/providers/vmware/container_manager.rb
  app/models/manageiq/providers/vmware/infra_manager.rb
Labels: refactoring

#768 Set VM description from summary.config.annotation
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/virtual_machine.rb
Labels: enhancement

#769 Add support for changing VM description
  app/models/manageiq/providers/vmware/infra_manager.rb
  app/models/manageiq/providers/vmware/infra_manager/vm_or_template_shared.rb
  app/models/manageiq/providers/vmware/infra_manager/vm_or_template_shared/operations.rb
Labels: enhancement

#770 Fix supports not working in vm_or_template_shared
  app/models/manageiq/providers/vmware/infra_manager/template.rb
  app/models/manageiq/providers/vmware/infra_manager/vm.rb
  app/models/manageiq/providers/vmware/infra_manager/vm_or_template_shared.rb
Labels: bug

#765 Delay WaitForUpdates and save in one thread to prevent "update storm" causing saver thread to be backed up
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/saver.rb
  app/models/manageiq/providers/vmware/infra_manager/refresh_worker/runner.rb
  app/models/manageiq/providers/vmware/infra_manager/refresher.rb
  config/settings.yml
  spec/models/manageiq/providers/vmware/infra_manager/inventory/parser_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
Labels: bug

#771 Add specs showing ems_custom_attribute bug
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
Labels: bug, test, lasker/yes?, morphy/yes?

#772 Only delay if wait_for_updates took less than poll_time
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
Labels: enhancement

#774 Fix vCloud snapshots find_or_build keys
  app/models/manageiq/providers/vmware/inventory/parser.rb
Labels: bug

#773 Allow collection of disconnected hosts in inventory
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/host_system.rb
Labels: enhancement

#775 Fix wrongly named spec files
  spec/models/manageiq/providers/vmware/infra_manager/ems_ref_obj_mixin_spec.rb
Labels: bug, test
