Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2021-02, with the labels that each got.

#697 Make Host#refresh_firewall_rules operate via SupportsFeatureMixin
  app/models/manageiq/providers/vmware/infra_manager/host_esx.rb
Labels: refactoring

#695 Clear cached tags after finishing a full refresh
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/virtual_machine.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
Labels: bug, kasparov/yes?

#698 Make Host#refresh_advanced_settings operate via SupportsFeatureMixin
  app/models/manageiq/providers/vmware/infra_manager/host_esx.rb
Labels: refactoring

#699 Make Host#refresh_logs operate via SupportsFeatureMixin
  app/models/manageiq/providers/vmware/infra_manager/host_esx.rb
Labels: refactoring

#696 Fix Rubocop issues in the new refresher code
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector/property_collector.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/datastore.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/host_system.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/virtual_machine.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/saver.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
Labels: technical debt

#700 Move save_inventory thread out of the inventory collector
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/saver.rb
  app/models/manageiq/providers/vmware/infra_manager/refresh_worker/runner.rb
  app/models/manageiq/providers/vmware/infra_manager/refresher.rb
  spec/models/manageiq/providers/vmware/infra_manager/inventory/parser_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
Labels: bug

#701 Convert `supports_#{op}?` to `supports?(op)`
  app/models/manageiq/providers/vmware/cloud_manager/vm/operations.rb
  app/models/manageiq/providers/vmware/cloud_manager/vm/operations/snapshot.rb
  app/models/manageiq/providers/vmware/infra_manager/template.rb
  app/models/manageiq/providers/vmware/infra_manager/vm/operations/guest.rb
  app/models/manageiq/providers/vmware/infra_manager/vm/operations/snapshot.rb
  app/models/manageiq/providers/vmware/infra_manager/vm_or_template_shared/operations.rb
  spec/models/manageiq/providers/vmware/cloud_manager_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/template_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/vm_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager_spec.rb
Labels: refactoring

#702 Adjust empty/initial values for select fields in DDF schemas
  app/models/manageiq/providers/vmware/cloud_manager.rb
Labels: enhancement
