Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2022-09, with the labels that each got.

#819 Refactor cloud network factories from core
  spec/factories/cloud_network.rb
Labels: test, refactoring

#821 convert create_guid_miq_server_zone to local_miq_server
  spec/factories/ext_management_system.rb
  spec/models/manageiq/providers/vmware/cloud_manager/refresher_spec.rb
  spec/models/manageiq/providers/vmware/cloud_manager/vm/reconfigure_spec.rb
  spec/models/manageiq/providers/vmware/cloud_manager_spec.rb
  spec/models/manageiq/providers/vmware/container_manager/refresher_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/metric_capture_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/provision_workflow_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/vm/operations/snapshot_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager/vm/remote_console_spec.rb
  spec/models/manageiq/providers/vmware/infra_manager_spec.rb
Labels: test

#522 Add a pure-ruby event catcher for VMware
  workers/event_catcher/event_catcher.rb
  workers/event_catcher/event_parser.rb
  workers/event_catcher/worker
Labels: enhancement

#824 Test ruby 2.7/3.0
  .github/workflows/ci.yaml
Labels: test, ruby3

#826 Fix snapshot ems ref obj no method error
  app/models/manageiq/providers/vmware/infra_manager/ems_ref_obj_mixin.rb
  app/models/manageiq/providers/vmware/infra_manager/provision/cloning.rb
  spec/factories/resource_pool.rb
  spec/models/manageiq/providers/vmware/infra_manager/provision/cloning_spec.rb
Labels: bug, najdorf/yes?, oparin/yes?
