Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2022-02, with the labels that each got.

#786 Remove Hakiri
  README.md
Labels: cleanup, developer

#791 Switch to GitHub Actions
  .github/workflows/ci.yaml
  .travis.yml
  README.md
  bin/before_install
  bin/ci/after_script
  bin/setup
  manageiq-providers-vmware.gemspec
Labels: test, developer

#792 Add Build History Graph to README.md
  README.md
Labels: test, developer

#794 Cron for GitHub Actions
  .github/workflows/ci.yaml
Labels: test, developer

#789 Handle session timeout errors when exiting collector
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector/property_collector.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
Labels: bug, morphy/yes?, najdorf/yes?
