Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2023-09, with the labels that each got.

#881 Update actions/checkout version to v4
  .github/workflows/ci.yaml
Labels: dependencies

#882 Handle a HostSystem with missing product vendor
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser/host_system.rb
  spec/models/manageiq/providers/vmware/infra_manager/refresher_spec.rb
Labels: bug, petrosian/yes?

#883 Set sub_event_type for com.vmware.cns.tasks.updatevolume
  app/models/manageiq/providers/vmware/infra_manager/event_parser.rb
Labels: bug

#885 Override CloudManager#network_manager to define type
  app/models/manageiq/providers/vmware/cloud_manager.rb
Labels: technical debt

#886 Don't delegate NetworkManager#zone to parent_manager
  app/models/manageiq/providers/vmware/network_manager.rb
Labels: bug

#884 Bump rbvmomi2 to 3.7.0 for vSphere 8.0U2
  manageiq-providers-vmware.gemspec
Labels: enhancement, quinteros/yes?
