Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2023-03, with the labels that each got.

#859 make default credentials verify ws
  app/models/manageiq/providers/vmware/infra_manager/host_esx.rb
Labels: refactoring

#862 Fix wrong number of arguments delete_snapshot_by_description
  app/models/manageiq/providers/vmware/infra_manager/scanning/job.rb
Labels: bug, petrosian/yes?

#860 Set the VMwareWebService.logger
  lib/manageiq/providers/vmware/engine.rb
Labels: bug, petrosian/yes?

#863 Bump vmware_web_service v3.2.0
  manageiq-providers-vmware.gemspec
Labels: bug, petrosian/yes?

#851 Introducing params_for_update schema to Hosts
  app/models/manageiq/providers/vmware/infra_manager/host.rb
Labels: enhancement
