Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2023-02, with the labels that each got.

#849 Fix Host#vim_connect missing port, verify_ssl
  app/models/manageiq/providers/vmware/infra_manager/vim_connect_mixin.rb
Labels: bug, najdorf/yes?, oparin/yes?

#854 Fix MiqVim argument format for Scanning
  app/models/manageiq/providers/vmware/infra_manager/vm_or_template_shared/scanning.rb
Labels: bug, oparin/yes?

#855 [PETROSIAN] Lock the petrosian release branch to test with ruby 3.0
  .github/workflows/ci.yaml
Labels: test

#856 removing host discovery
  app/models/manageiq/providers/vmware/infra_manager/host.rb
Labels: technical debt
