Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2024-02, with the labels that each got.

#898 Drop require_nested and include_concern
  app/models/manageiq/providers/vmware/cloud_manager.rb
  app/models/manageiq/providers/vmware/cloud_manager/event_catcher.rb
  app/models/manageiq/providers/vmware/cloud_manager/orchestration_stack.rb
  app/models/manageiq/providers/vmware/cloud_manager/refresh_worker.rb
  app/models/manageiq/providers/vmware/cloud_manager/vm.rb
  app/models/manageiq/providers/vmware/cloud_manager/vm/operations.rb
  app/models/manageiq/providers/vmware/container_manager.rb
  app/models/manageiq/providers/vmware/container_manager/event_catcher.rb
  app/models/manageiq/providers/vmware/container_manager/refresh_worker.rb
  app/models/manageiq/providers/vmware/infra_manager.rb
  app/models/manageiq/providers/vmware/infra_manager/event_catcher.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb
  app/models/manageiq/providers/vmware/infra_manager/inventory/persister.rb
  app/models/manageiq/providers/vmware/infra_manager/metrics_collector_worker.rb
  app/models/manageiq/providers/vmware/infra_manager/operations_worker.rb
  app/models/manageiq/providers/vmware/infra_manager/provision.rb
  app/models/manageiq/providers/vmware/infra_manager/provision/configuration.rb
  app/models/manageiq/providers/vmware/infra_manager/provision_via_pxe.rb
  app/models/manageiq/providers/vmware/infra_manager/provision_workflow.rb
  app/models/manageiq/providers/vmware/infra_manager/refresh_worker.rb
  app/models/manageiq/providers/vmware/infra_manager/scanning.rb
  app/models/manageiq/providers/vmware/infra_manager/template.rb
  app/models/manageiq/providers/vmware/infra_manager/vm.rb
  app/models/manageiq/providers/vmware/infra_manager/vm/operations.rb
  app/models/manageiq/providers/vmware/infra_manager/vm_or_template_shared.rb
  app/models/manageiq/providers/vmware/infra_manager/vm_or_template_shared/operations.rb
  app/models/manageiq/providers/vmware/inventory.rb
  app/models/manageiq/providers/vmware/inventory/collector.rb
  app/models/manageiq/providers/vmware/inventory/collector/container_manager.rb
  app/models/manageiq/providers/vmware/inventory/parser.rb
  app/models/manageiq/providers/vmware/inventory/parser/container_manager.rb
  app/models/manageiq/providers/vmware/inventory/persister.rb
  app/models/manageiq/providers/vmware/inventory/persister/container_manager.rb
  app/models/manageiq/providers/vmware/network_manager.rb
  app/models/manageiq/providers/vmware/network_manager/cloud_network.rb
Labels: technical debt, rails7

#899 Set minimum version to support rails 7
  manageiq-providers-vmware.gemspec
Labels: rails7

#900 Test with ruby 3.1 and 3.0
  .github/workflows/ci.yaml
Labels: test

#895 Fix Host default_authentication_type
  app/models/manageiq/providers/vmware/infra_manager/host.rb
  app/models/manageiq/providers/vmware/infra_manager/vim_connect_mixin.rb
Labels: bug, quinteros/yes?

#902 [RADJABOV] Test radjabov with ruby 3.1
  .github/workflows/ci.yaml
Labels: test, ruby3.1

#901 drop unsupported_reason_add
  app/models/manageiq/providers/vmware/cloud_manager/vm.rb
  app/models/manageiq/providers/vmware/cloud_manager/vm/operations.rb
  app/models/manageiq/providers/vmware/infra_manager.rb
  app/models/manageiq/providers/vmware/infra_manager/host.rb
  app/models/manageiq/providers/vmware/infra_manager/host_esx.rb
  app/models/manageiq/providers/vmware/infra_manager/template.rb
  app/models/manageiq/providers/vmware/infra_manager/vm.rb
  app/models/manageiq/providers/vmware/infra_manager/vm/operations/guest.rb
  app/models/manageiq/providers/vmware/infra_manager/vm_or_template_shared/operations/relocation.rb
  app/models/manageiq/providers/vmware/infra_manager/vm_or_template_shared/scanning.rb
Labels: technical debt, radjabov/yes?
