Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2024-01, with the labels that each got.

#887 Add supports storage smartstate_analysis
  app/models/manageiq/providers/vmware/infra_manager/vm_or_template_shared/scanning.rb
Labels: bug, quinteros/yes?

#894 Enable non-rails event catcher by default
  config/settings.yml
Labels: enhancement, quinteros/yes?

#897 Fix VM terminate showing supported when running
  app/models/manageiq/providers/vmware/infra_manager/template/operations.rb
  app/models/manageiq/providers/vmware/infra_manager/vm/operations.rb
  app/models/manageiq/providers/vmware/infra_manager/vm_or_template_shared/operations.rb
  spec/models/manageiq/providers/vmware/infra_manager/vm_spec.rb
Labels: bug
