Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2024-11, with the labels that each got.

#923 Testing with ruby 3.2, 3.3
  .github/workflows/ci.yaml
Labels: test, ruby3.3

#925 Delegate refresh_ems class method to parent cloud manager
  app/models/manageiq/providers/vmware/network_manager.rb
  config/settings.yml
Labels: bug, radjabov/yes?

#924 Bump ffi-vix_disklib to v1.4 for v8.0.3 support
  manageiq-providers-vmware.gemspec
Labels: dependencies, radjabov/yes?
