Repository ManageIQ/manageiq-providers-vmware, pull requests merged in 2024-07, with the labels that each got.

#915 remove return from supports blocks
  app/models/manageiq/providers/vmware/infra_manager/vm/operations/guest.rb
Labels: bug

#916 Add VMware vSphere 8.0U3 support
  manageiq-providers-vmware.gemspec
Labels: enhancement, radjabov/yes?

#917 Continue refresh if cis_connect fails
  app/models/manageiq/providers/vmware/infra_manager/inventory/collector.rb
Labels: bug, radjabov/yes?
